### variable
@SERVER=http://localhost:60000


### testing the server
GET {{SERVER}}


### register stock manager
POST {{SERVER}}/api/users/register
content-type: application/json

{
    "name": "Samkelisiwe",
    "email": "samke@shaper.co.za",
    "password": "123456"
}


### login
POST {{SERVER}}/api/users/login
content-type: application/json

{
    "email": "samke@shaper.co.za",
    "password": "123456"
}


### Add stock items
POST {{SERVER}}/api/stock/create
content-type: application/json

{
 "name": "broom",
 "description": "out of tock"
}

### Update stock items
PUT {{SERVER}}/api/stock/update/
content-type: application/json

{
 "name": "suger",
 "description": "out of tock"
}

### Delete stock items
DELETE {{SERVER}}/api/stock/remove/6569723b99fe685f8e280454
content-type: application/json

{
 "name": "broom",
 "description": "out of tock"
}







