### variable
@SERVER=http://localhost:60000


### testing the server
GET {{SERVER}}


### register stock manager
POST {{SERVER}}/api/users/register
content-type: application/json

{
    "name": "Samkelisiwe",
    "email": "samke@shaper.co.za",
    "password": "123456"
}


### login
POST {{SERVER}}/api/users/login
content-type: application/json

{
    "email": "samke@shaper.co.za",
    "password": "123456"
}


### Add stock items
POST {{SERVER}}/api/stock/create
content-type: application/json

{
 "name": "broom",
 "description": "out of tock"
}

### Update stock items
PUT {{SERVER}}/api/stock/items/6569746999fe685f8e28045a
content-type: application/json

{
 "name": "tails",
 "description": "in stock"
}

###Read###
GET {{SERVER}}/api/stock/items



###DELETE###
DELETE {{SERVER}}/api/stock/items/6569748d99fe685f8e28045c
content-type: application/json

{
 "name": "porish",
 "description": "in stock"
}

###Search###
GET {{SERVER}}/api/stock/items/6569748d99fe685f8e28045c






